name: Trigger auto deployment for stefan-test-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ testing ]
    paths:
    - '**'
    - '.github/workflows/stefan-test-dev-AutoDeployTrigger-09ab8c36-93ab-4fb5-870c-b773ca3da5f5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acryaba.azurecr.io
          username: ${{ secrets.STEFANTESTDEV_REGISTRY_USERNAME }}
          password: ${{ secrets.STEFANTESTDEV_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acryaba.azurecr.io/stefan-test-dev:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.STEFANTESTDEV_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n stefan-test-dev -g fpolido --server acryaba.azurecr.io --username  ${{ secrets.STEFANTESTDEV_REGISTRY_USERNAME }} --password ${{ secrets.STEFANTESTDEV_REGISTRY_PASSWORD }}
            az containerapp update -n stefan-test-dev -g fpolido --image acryaba.azurecr.io/stefan-test-dev:${{ github.sha }}
