name: Trigger auto deployment for test-stefan-github

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-stefan-github-AutoDeployTrigger-7ae566a9-5266-4d58-ab9a-38e525ea1fbd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acryaba.azurecr.io
          username: ${{ secrets.TESTSTEFANGITHUB_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTSTEFANGITHUB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acryaba.azurecr.io/test-stefan-github:${{ github.sha }}
          file: ./Dockerfile
          context: ./
